### PR TITLE
Refactor server

### PR DESCRIPTION
**Pull request by robinandeer**
I'll make some adjustments to the server code to clean it up and avoid duplication of code etc.

**Changes made so far:**

- Collected all server code under `puzzle/server`
- Added code in `view` subcommand to auto open a web browser tab

### CODE REVIEW

**Comment by moonso** [comment]
Think you should merge #128 and rebase first...

**Comment by robinandeer** [comment]
True! Sorry but I think it will work bc you don't touch the server code in the PR - I'll give it a go :)

**Comment by moonso** [comment]
Ok! It would be nice to add some tests to this part of the code, could we do that in this PR?

**Comment by robinandeer** [comment]
I was thinking about that but I will start with restructuring the code

**Comment by moonso** [comment]
Ok :four_leaf_clover:

**Comment by robinandeer** [comment]
That was painless - no merge conflicts and all tests pass locally :)

**Comment by moonso** [comment]
Nice!

**Comment by moonso** [comment]
Is this PR done?

**Comment by robinandeer** [comment]
If anyone has time to review then go ahead!
Might be nice bc it's all structure pretty much and not much else has changed

**Comment by moonso** [comment]
I have reviewed and think it looks fine. Nice that you added some docstrings!

**Pull request merged**
