### PR TITLE
Can run user defined gemini queries. fix #153

### LINKED ISSUE #153: Allow custom gemini queries
User should be able to define gemini queries in filter window

### PR DESCRIPTION
**Pull request by moonso**

### CODE REVIEW

**Comment by guillermo-carrasco** [comment]
Oh, this is nice @moonso !!

**Comment by moonso** [comment]
Yes but @robinandeer should have cred to :camel:

**Comment by moonso** [comment]
Please merge @guillermo-carrasco !!

**Comment by robinandeer** [comment]
tooo slow @guillermo-carrasco !!

**Pull request merged**
