### PR TITLE
Quick check for missing hgnc lookup.

### PR DESCRIPTION
**Pull request by dnil**

### CODE REVIEW

**Comment by dnil** [comment]
Ahem, and sorry for leaving that in "master" - didn't really intend to do it myself initially.. :)

**Comment by moonso** [comment]
No problem, if you master works it is all good!

**Comment by moonso** [comment]
*your* master

**Comment by moonso** [comment]
I've just made small modifications to your changes by using ```.get``` in a better way.
Thank you for spotting and fixing this!

changed:

```python
hgnc = HGNC_TO_OMIM.get(hgnc_symbol)

if hgnc is not None:
    omim_number = hgnc.get('mim_nr')
else:
    omim_number = None

return omim_number
```
to 

```python
omim_number =  HGNC_TO_OMIM.get(hgnc_symbol, {}).get('mim_nr')

return omim_number
```

and same in other function:)

**Comment by dnil** [comment]
Nice! 

I might suggest to reintroduce a fictive gene symbol to the tests and ensure they are handled (logged?) but don’t break the experience?
Actually MCCRP2 != PLK4 for MIM#605031 could be a nice example.. :)

**Comment by moonso** [comment]
I'm writing some tests for this now so we can look at it tomorrow

**Pull request merged**
