### PR TITLE
Example of using dataTables (js) for interactive table listings

### PR DESCRIPTION
**Pull request by vasiliosz**
This uses dataTables (http://datatables.net) for client-side sorting/filtering of tables. This branch is just an example of how to implement it. There are lots more options/plugins/customizations possible if needed. 

I’ve only added it to the SV-mode now.

Some issues: 
- the sorting of `sv_len` does not work properly, something to do with `NA` length-values (coded as `Inf` in puzzle)

### CODE REVIEW

**Comment by vasiliosz** [comment]
The tests fail because I corrected the naming of cytobands to remove the `.` (dot) between chr and cytoband

**Comment by moonso** [comment]
Nice @vasiliosz !! 
What do you think about adding dataTables @robinandeer ?
I have no opinion since I have to little experience in html

**Comment by vasiliosz** [comment]
I dropped the non-datatable commits, will submit them separately

**Comment by robinandeer** [comment]
@vasiliosz: any idea why is says `robinandeer:master from unknown repository` above? 

ping @guillermo-carrasco

**Comment by vasiliosz** [comment]
Yes @robinandeer, sorry about that. Something went wrong with the fork (merge conflicts) and I re-forked it, leaving this stale. I thought this would not matter since this pull request was quite old anyway. 

I can re-open it as a fresh one?

**Comment by robinandeer** [comment]
@guillermo-carrasco is trying to get it working here: 4fded67876699b5

**Comment by moonso** [comment]
Should we close this PR if we are reimplementing it anyway?

**Comment by robinandeer** [comment]
Yeah, I think we have to anyways bc of the closed fork :)

**Comment by vasiliosz** [comment]
:sweat_smile: Sorry about that. I'll send a new PR with this basic implementation...

**Comment by moonso** [comment]
:+1:

**Pull request closed without merging**
