### PR TITLE
Added an IGV goto URL for the variant view.

### PR DESCRIPTION
**Pull request by dnil**
I found this useful when browsing variants locally. Assuming I can open a bam file in IGV somehow, I can jump directly to the right spot from puzzle. The http interface allows loading as well, but then one needs to decide on how/where to put the bam data. https://www.broadinstitute.org/igv/ControlIGV

### CODE REVIEW

**Comment by moonso** [comment]
Thanks @dnil :+1: , think it's best if @robinandeer have a look and merge this one.

**Comment by moonso** [comment]
So I've tried this one out but didn't really understand what to do..
Could you include a small example and how to run it @dnil ?

**Comment by vasiliosz** [comment]
@moonso: You can open any file (i.e. BAM or other) in IGV. Make sure to have the port open in IGV's settings (60151 is default). Then the url scheme @dnil added should work

inklistrad_bild_18_10_15_15_45

**Comment by moonso** [comment]
Ok I'll try that!

**Comment by moonso** [comment]
@vasiliosz could you help me with a gemini query to get all variants for a particular family?

**Comment by vasiliosz** [comment]
For the built-in tools (`comp_hets` etc) there is the `--families family1,family2` flag . 
For a general query I think you can use the `--sample-filter` flag: 
(more in the [GEMINI manual](https://gemini.readthedocs.org/en/latest/content/querying.html#sample-filter-restrict-a-query-to-specified-samples))

Ex 
```
gemini query --sample-filter "family_id='family101'"  -q "select * from variants" gemini.db 
```

**Comment by moonso** [comment]
Thank you @vasiliosz !

It would still be nice  to add a small BAM file in test/fixtures with reads that overlapps variants from any of the existing vcf:s or a new one for testing.

**Comment by dnil** [comment]
Sure, nice idea! I can extract reads from around a few variant positions for the IonTorrent test one to make it a little more portable!

**Comment by moonso** [comment]
Thank you @dnil it should work on the master branch now :smile:

**Pull request closed without merging**
