### PR TITLE
[WIP] Refactoring: Testing utils

### PR DESCRIPTION
**Pull request by guillermo-carrasco**
This is a refactoring of the utils module testing. Not fully completed and haven't added any new test _yet_. Just restructured to a class-per-submodule based structure :-). Please let me know what you think.

### CODE REVIEW

**Comment by robinandeer** [comment]
I was a little bit sceptical at first since the test classes actually don't do any setup/teardown but I like how it give everything a clear structure -- good idea!

**Comment by moonso** [comment]
Looks great, just merge it :sunflower:

**Comment by guillermo-carrasco** [comment]
Great, thanks! My first contribution! :tada:

**Comment by moonso** [comment]
:birthday:

**Pull request merged**
