### PR TITLE
Filter fixes: enable SV len filter and max_freq setting on VCF.

### PR DESCRIPTION
**Pull request by dnil**
SV len filter was turned off by default. Also, max_freq was not set for variants pulled through VCF adaptor.

Snuck in SV variant freq display already at the SV variants page, and an extra link to better indicate that there (may) be more OMIM genes hiding in a multi gene event than meets the eye on the variants list.

### CODE REVIEW

**Comment by moonso** [comment]
Great! There is a huge PR, #141, that messes up the VCF adapter alot.
But I also added the max_freq thing there.
Could we wait for that before merging this?

**Comment by dnil** [comment]
Oh my! Sure thing - looks good!

**Comment by dnil** [comment]
Really nice and fast it is, #141! I'll rebase - it's just a few lines left now I think!

**Comment by moonso** [comment]
:+1:

**Pull request closed without merging**
