### PR TITLE
Fix vcf gene filter

### LINKED ISSUE #214: Gene list searching appears to default to wildcard
this becomes cumbersome for genes with short names (like AR or T) or genes in gene-families where one may want see TMEM5 but not TMEM52.

### PR DESCRIPTION
**Pull request by dnil**
Fixes #214.

### CODE REVIEW

**Comment by moonso** [comment]
:+1:  could you update the test `tests/plugins/vcf/test_vcf_variant_mixin.py` before merging?

**Comment by dnil** [comment]
ah, thanks, good point! at a meeting today; will look it up later!

**Comment by moonso** [comment]
So @dnil would you like to fix the test? We can not alter your pull request...

**Comment by dnil** [comment]
Made obsolete by #224.

**Pull request closed without merging**
